yarnPath: .yarn/releases/yarn-4.0.2.cjs

nodeLinker: node-modules

npmScopes:
  rammble:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"