import {
  neutral,
  neutralAlpha,
  neutralLight,
  neutralLightAlpha,
} from 'src/theme/colors/neutral'
import {
  accent,
  accentAlpha,
  accentLight,
  accentLightAlpha,
} from 'src/theme/colors/accent'
import {
  error,
  errorAlpha,
  errorLight,
  errorLightAlpha,
} from 'src/theme/colors/error'
import {
  success,
  successAlpha,
  successLight,
  successLightAlpha,
} from 'src/theme/colors/success'
import {
  warn,
  warnAlpha,
  warnLight,
  warnLightAlpha,
} from 'src/theme/colors/warn'
import {
  info,
  infoAlpha,
  infoLight,
  infoLightAlpha,
} from 'src/theme/colors/info'

const rawColors = {
  accent: {
    dark: {
      1: accent[0],
      2: accent[1],
      3: accent[2],
      4: accent[3],
      5: accent[4],
      6: accent[5],
      7: accent[6],
      8: accent[7],
      9: accent[8],
      10: accent[9],
      11: accent[10],
      12: accent[11],
      '1a': accentAlpha[0],
      '2a': accentAlpha[1],
      '3a': accentAlpha[2],
      '4a': accentAlpha[3],
      '5a': accentAlpha[4],
      '6a': accentAlpha[5],
      '7a': accentAlpha[6],
      '8a': accentAlpha[7],
      '9a': accentAlpha[8],
      '10a': accentAlpha[9],
      '11a': accentAlpha[10],
      '12a': accentAlpha[11],
    },
    light: {
      1: accentLight[0],
      2: accentLight[1],
      3: accentLight[2],
      4: accentLight[3],
      5: accentLight[4],
      6: accentLight[5],
      7: accentLight[6],
      8: accentLight[7],
      9: accentLight[8],
      10: accentLight[9],
      11: accentLight[10],
      12: accentLight[11],
      '1a': accentLightAlpha[0],
      '2a': accentLightAlpha[1],
      '3a': accentLightAlpha[2],
      '4a': accentLightAlpha[3],
      '5a': accentLightAlpha[4],
      '6a': accentLightAlpha[5],
      '7a': accentLightAlpha[6],
      '8a': accentLightAlpha[7],
      '9a': accentLightAlpha[8],
      '10a': accentLightAlpha[9],
      '11a': accentLightAlpha[10],
      '12a': accentLightAlpha[11],
    },
  },
  neutral: {
    dark: {
      1: neutral[0],
      2: neutral[1],
      3: neutral[2],
      4: neutral[3],
      5: neutral[4],
      6: neutral[5],
      7: neutral[6],
      8: neutral[7],
      9: neutral[8],
      10: neutral[9],
      11: neutral[10],
      12: neutral[11],
      '1a': neutralAlpha[0],
      '2a': neutralAlpha[1],
      '3a': neutralAlpha[2],
      '4a': neutralAlpha[3],
      '5a': neutralAlpha[4],
      '6a': neutralAlpha[5],
      '7a': neutralAlpha[6],
      '8a': neutralAlpha[7],
      '9a': neutralAlpha[8],
      '10a': neutralAlpha[9],
      '11a': neutralAlpha[10],
      '12a': neutralAlpha[11],
    },
    light: {
      1: neutralLight[0],
      2: neutralLight[1],
      3: neutralLight[2],
      4: neutralLight[3],
      5: neutralLight[4],
      6: neutralLight[5],
      7: neutralLight[6],
      8: neutralLight[7],
      9: neutralLight[8],
      10: neutralLight[9],
      11: neutralLight[10],
      12: neutralLight[11],
      '1a': neutralLightAlpha[0],
      '2a': neutralLightAlpha[1],
      '3a': neutralLightAlpha[2],
      '4a': neutralLightAlpha[3],
      '5a': neutralLightAlpha[4],
      '6a': neutralLightAlpha[5],
      '7a': neutralLightAlpha[6],
      '8a': neutralLightAlpha[7],
      '9a': neutralLightAlpha[8],
      '10a': neutralLightAlpha[9],
      '11a': neutralLightAlpha[10],
      '12a': neutralLightAlpha[11],
    },
  },
  error: {
    dark: {
      1: error[0],
      2: error[1],
      3: error[2],
      4: error[3],
      5: error[4],
      6: error[5],
      7: error[6],
      8: error[7],
      9: error[8],
      10: error[9],
      11: error[10],
      12: error[11],
      '1a': errorAlpha[0],
      '2a': errorAlpha[1],
      '3a': errorAlpha[2],
      '4a': errorAlpha[3],
      '5a': errorAlpha[4],
      '6a': errorAlpha[5],
      '7a': errorAlpha[6],
      '8a': errorAlpha[7],
      '9a': errorAlpha[8],
      '10a': errorAlpha[9],
      '11a': errorAlpha[10],
      '12a': errorAlpha[11],
    },
    light: {
      1: errorLight[0],
      2: errorLight[1],
      3: errorLight[2],
      4: errorLight[3],
      5: errorLight[4],
      6: errorLight[5],
      7: errorLight[6],
      8: errorLight[7],
      9: errorLight[8],
      10: errorLight[9],
      11: errorLight[10],
      12: errorLight[11],
      '1a': errorLightAlpha[0],
      '2a': errorLightAlpha[1],
      '3a': errorLightAlpha[2],
      '4a': errorLightAlpha[3],
      '5a': errorLightAlpha[4],
      '6a': errorLightAlpha[5],
      '7a': errorLightAlpha[6],
      '8a': errorLightAlpha[7],
      '9a': errorLightAlpha[8],
      '10a': errorLightAlpha[9],
      '11a': errorLightAlpha[10],
      '12a': errorLightAlpha[11],
    },
  },
  success: {
    dark: {
      1: success[0],
      2: success[1],
      3: success[2],
      4: success[3],
      5: success[4],
      6: success[5],
      7: success[6],
      8: success[7],
      9: success[8],
      10: success[9],
      11: success[10],
      12: success[11],
      '1a': successAlpha[0],
      '2a': successAlpha[1],
      '3a': successAlpha[2],
      '4a': successAlpha[3],
      '5a': successAlpha[4],
      '6a': successAlpha[5],
      '7a': successAlpha[6],
      '8a': successAlpha[7],
      '9a': successAlpha[8],
      '10a': successAlpha[9],
      '11a': successAlpha[10],
      '12a': successAlpha[11],
    },
    light: {
      1: successLight[0],
      2: successLight[1],
      3: successLight[2],
      4: successLight[3],
      5: successLight[4],
      6: successLight[5],
      7: successLight[6],
      8: successLight[7],
      9: successLight[8],
      10: successLight[9],
      11: successLight[10],
      12: successLight[11],
      '1a': successLightAlpha[0],
      '2a': successLightAlpha[1],
      '3a': successLightAlpha[2],
      '4a': successLightAlpha[3],
      '5a': successLightAlpha[4],
      '6a': successLightAlpha[5],
      '7a': successLightAlpha[6],
      '8a': successLightAlpha[7],
      '9a': successLightAlpha[8],
      '10a': successLightAlpha[9],
      '11a': successLightAlpha[10],
      '12a': successLightAlpha[11],
    },
  },
  warn: {
    dark: {
      1: warn[0],
      2: warn[1],
      3: warn[2],
      4: warn[3],
      5: warn[4],
      6: warn[5],
      7: warn[6],
      8: warn[7],
      9: warn[8],
      10: warn[9],
      11: warn[10],
      12: warn[11],
      '1a': warnAlpha[0],
      '2a': warnAlpha[1],
      '3a': warnAlpha[2],
      '4a': warnAlpha[3],
      '5a': warnAlpha[4],
      '6a': warnAlpha[5],
      '7a': warnAlpha[6],
      '8a': warnAlpha[7],
      '9a': warnAlpha[8],
      '10a': warnAlpha[9],
      '11a': warnAlpha[10],
      '12a': warnAlpha[11],
    },
    light: {
      1: warnLight[0],
      2: warnLight[1],
      3: warnLight[2],
      4: warnLight[3],
      5: warnLight[4],
      6: warnLight[5],
      7: warnLight[6],
      8: warnLight[7],
      9: warnLight[8],
      10: warnLight[9],
      11: warnLight[10],
      12: warnLight[11],
      '1a': warnLightAlpha[0],
      '2a': warnLightAlpha[1],
      '3a': warnLightAlpha[2],
      '4a': warnLightAlpha[3],
      '5a': warnLightAlpha[4],
      '6a': warnLightAlpha[5],
      '7a': warnLightAlpha[6],
      '8a': warnLightAlpha[7],
      '9a': warnLightAlpha[8],
      '10a': warnLightAlpha[9],
      '11a': warnLightAlpha[10],
      '12a': warnLightAlpha[11],
    },
  },
  info: {
    dark: {
      1: info[0],
      2: info[1],
      3: info[2],
      4: info[3],
      5: info[4],
      6: info[5],
      7: info[6],
      8: info[7],
      9: info[8],
      10: info[9],
      11: info[10],
      12: info[11],
      '1a': infoAlpha[0],
      '2a': infoAlpha[1],
      '3a': infoAlpha[2],
      '4a': infoAlpha[3],
      '5a': infoAlpha[4],
      '6a': infoAlpha[5],
      '7a': infoAlpha[6],
      '8a': infoAlpha[7],
      '9a': infoAlpha[8],
      '10a': infoAlpha[9],
      '11a': infoAlpha[10],
      '12a': infoAlpha[11],
    },
    light: {
      1: infoLight[0],
      2: infoLight[1],
      3: infoLight[2],
      4: infoLight[3],
      5: infoLight[4],
      6: infoLight[5],
      7: infoLight[6],
      8: infoLight[7],
      9: infoLight[8],
      10: infoLight[9],
      11: infoLight[10],
      12: infoLight[11],
      '1a': infoLightAlpha[0],
      '2a': infoLightAlpha[1],
      '3a': infoLightAlpha[2],
      '4a': infoLightAlpha[3],
      '5a': infoLightAlpha[4],
      '6a': infoLightAlpha[5],
      '7a': infoLightAlpha[6],
      '8a': infoLightAlpha[7],
      '9a': infoLightAlpha[8],
      '10a': infoLightAlpha[9],
      '11a': infoLightAlpha[10],
      '12a': infoLightAlpha[11],
    },
  },
} as const

export const colors = {
  panel: {
    background: {
      dark: '#121217',
      light: '#F6FAFF',
    },
    solid: {
      dark: '#202029',
      light: '#ffffff',
    },
    default: {
      dark: '#1D1D21B2',
      light: '#0000001A', // TODO: CHANGE THIS TO CORRECT COLOR
    },
  },
  text: {
    dark: '#edf4fa',
    light: '#02111f',
  },
  contrast: {
    black: '#02111f',
    white: '#edf4fa',
  },
  surface: {
    dark: '#00000040',
    light: '#FFFFFFE5',
  },
  'surface-accent': {
    dark: '#17324B07',
    light: '#17324B07',
  },
  ...rawColors,
} as const

const semanticMode = (
  name: keyof typeof rawColors,
  key: `${keyof (typeof rawColors)[keyof typeof rawColors]['dark' | 'light']}`,
) =>
  ({
    _dark: rawColors[name].dark[key],
    _light: rawColors[name].light[key],
  }) as const

export const semanticTokens = {
  colors: {
    panel: {
      background: {
        _dark: colors.panel.background.dark,
        _light: colors.panel.background.light,
      },
      solid: {
        _dark: colors.panel.solid.dark,
        _light: colors.panel.solid.light,
      },
      default: {
        _dark: colors.panel.default.dark,
        _light: colors.panel.default.light,
      },
    },
    text: {
      _dark: colors.text.dark,
      _light: colors.text.light,
    },
    surface: {
      _dark: colors.surface.dark,
      _light: colors.surface.light,
    },
    contrast: {
      white: {
        _dark: colors.contrast.white,
        _light: colors.contrast.white,
      },
      black: {
        _dark: colors.contrast.black,
        _light: colors.contrast.black,
      },
    },
    accent: {
      '1': semanticMode('accent', '1'),
      '2': semanticMode('accent', '2'),
      '3': semanticMode('accent', '3'),
      '4': semanticMode('accent', '4'),
      '5': semanticMode('accent', '5'),
      '6': semanticMode('accent', '6'),
      '7': semanticMode('accent', '7'),
      '8': semanticMode('accent', '8'),
      '9': semanticMode('accent', '9'),
      '10': semanticMode('accent', '10'),
      '11': semanticMode('accent', '11'),
      '12': semanticMode('accent', '12'),
      '1a': semanticMode('accent', '1a'),
      '2a': semanticMode('accent', '2a'),
      '3a': semanticMode('accent', '3a'),
      '4a': semanticMode('accent', '4a'),
      '5a': semanticMode('accent', '5a'),
      '6a': semanticMode('accent', '6a'),
      '7a': semanticMode('accent', '7a'),
      '8a': semanticMode('accent', '8a'),
      '9a': semanticMode('accent', '9a'),
      '10a': semanticMode('accent', '10a'),
      '11a': semanticMode('accent', '11a'),
      '12a': semanticMode('accent', '12a'),
    },
    neutral: {
      '1': semanticMode('neutral', '1'),
      '2': semanticMode('neutral', '2'),
      '3': semanticMode('neutral', '3'),
      '4': semanticMode('neutral', '4'),
      '5': semanticMode('neutral', '5'),
      '6': semanticMode('neutral', '6'),
      '7': semanticMode('neutral', '7'),
      '8': semanticMode('neutral', '8'),
      '9': semanticMode('neutral', '9'),
      '10': semanticMode('neutral', '10'),
      '11': semanticMode('neutral', '11'),
      '12': semanticMode('neutral', '12'),
      '1a': semanticMode('neutral', '1a'),
      '2a': semanticMode('neutral', '2a'),
      '3a': semanticMode('neutral', '3a'),
      '4a': semanticMode('neutral', '4a'),
      '5a': semanticMode('neutral', '5a'),
      '6a': semanticMode('neutral', '6a'),
      '7a': semanticMode('neutral', '7a'),
      '8a': semanticMode('neutral', '8a'),
      '9a': semanticMode('neutral', '9a'),
      '10a': semanticMode('neutral', '10a'),
      '11a': semanticMode('neutral', '11a'),
      '12a': semanticMode('neutral', '12a'),
    },
    error: {
      '1': semanticMode('error', '1'),
      '2': semanticMode('error', '2'),
      '3': semanticMode('error', '3'),
      '4': semanticMode('error', '4'),
      '5': semanticMode('error', '5'),
      '6': semanticMode('error', '6'),
      '7': semanticMode('error', '7'),
      '8': semanticMode('error', '8'),
      '9': semanticMode('error', '9'),
      '10': semanticMode('error', '10'),
      '11': semanticMode('error', '11'),
      '12': semanticMode('error', '12'),
      '1a': semanticMode('error', '1a'),
      '2a': semanticMode('error', '2a'),
      '3a': semanticMode('error', '3a'),
      '4a': semanticMode('error', '4a'),
      '5a': semanticMode('error', '5a'),
      '6a': semanticMode('error', '6a'),
      '7a': semanticMode('error', '7a'),
      '8a': semanticMode('error', '8a'),
      '9a': semanticMode('error', '9a'),
      '10a': semanticMode('error', '10a'),
      '11a': semanticMode('error', '11a'),
      '12a': semanticMode('error', '12a'),
    },
    success: {
      '1': semanticMode('success', '1'),
      '2': semanticMode('success', '2'),
      '3': semanticMode('success', '3'),
      '4': semanticMode('success', '4'),
      '5': semanticMode('success', '5'),
      '6': semanticMode('success', '6'),
      '7': semanticMode('success', '7'),
      '8': semanticMode('success', '8'),
      '9': semanticMode('success', '9'),
      '10': semanticMode('success', '10'),
      '11': semanticMode('success', '11'),
      '12': semanticMode('success', '12'),
      '1a': semanticMode('success', '1a'),
      '2a': semanticMode('success', '2a'),
      '3a': semanticMode('success', '3a'),
      '4a': semanticMode('success', '4a'),
      '5a': semanticMode('success', '5a'),
      '6a': semanticMode('success', '6a'),
      '7a': semanticMode('success', '7a'),
      '8a': semanticMode('success', '8a'),
      '9a': semanticMode('success', '9a'),
      '10a': semanticMode('success', '10a'),
      '11a': semanticMode('success', '11a'),
      '12a': semanticMode('success', '12a'),
    },
    warn: {
      '1': semanticMode('warn', '1'),
      '2': semanticMode('warn', '2'),
      '3': semanticMode('warn', '3'),
      '4': semanticMode('warn', '4'),
      '5': semanticMode('warn', '5'),
      '6': semanticMode('warn', '6'),
      '7': semanticMode('warn', '7'),
      '8': semanticMode('warn', '8'),
      '9': semanticMode('warn', '9'),
      '10': semanticMode('warn', '10'),
      '11': semanticMode('warn', '11'),
      '12': semanticMode('warn', '12'),
      '1a': semanticMode('warn', '1a'),
      '2a': semanticMode('warn', '2a'),
      '3a': semanticMode('warn', '3a'),
      '4a': semanticMode('warn', '4a'),
      '5a': semanticMode('warn', '5a'),
      '6a': semanticMode('warn', '6a'),
      '7a': semanticMode('warn', '7a'),
      '8a': semanticMode('warn', '8a'),
      '9a': semanticMode('warn', '9a'),
      '10a': semanticMode('warn', '10a'),
      '11a': semanticMode('warn', '11a'),
      '12a': semanticMode('warn', '12a'),
    },
    info: {
      '1': semanticMode('info', '1'),
      '2': semanticMode('info', '2'),
      '3': semanticMode('info', '3'),
      '4': semanticMode('info', '4'),
      '5': semanticMode('info', '5'),
      '6': semanticMode('info', '6'),
      '7': semanticMode('info', '7'),
      '8': semanticMode('info', '8'),
      '9': semanticMode('info', '9'),
      '10': semanticMode('info', '10'),
      '11': semanticMode('info', '11'),
      '12': semanticMode('info', '12'),
      '1a': semanticMode('info', '1a'),
      '2a': semanticMode('info', '2a'),
      '3a': semanticMode('info', '3a'),
      '4a': semanticMode('info', '4a'),
      '5a': semanticMode('info', '5a'),
      '6a': semanticMode('info', '6a'),
      '7a': semanticMode('info', '7a'),
      '8a': semanticMode('info', '8a'),
      '9a': semanticMode('info', '9a'),
      '10a': semanticMode('info', '10a'),
      '11a': semanticMode('info', '11a'),
      '12a': semanticMode('info', '12a'),
    },
  },
}
