name: Create and publish a Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      is_version_mismatch: ${{ steps.last_updated_image.outputs.value != steps.pkg.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package.json version
        id: pkg
        run: |
          echo ::set-output name=version::$(node -p "require('./package.json').version")

      - id: last_updated_image
        run: |
          echo "value=$( \
            curl -H "Authorization: Bearer ${{ secrets.READ_PKG_PAT }}" \
                -H 'Accept: application/vnd.github.everest-preview+json' \
                -H 'X-GitHub-Api-Version: 2022-11-28' \
                "https://api.github.com/orgs/rammble/packages/container/web/versions" \
                | jq -r 'del(.[0].metadata.container.tags[] | select(. == "latest"))[0].metadata.container.tags[0]' \
          )" >> $GITHUB_OUTPUT

      - name: Output versions
        run: |
          echo "Last updated image: ${{ steps.last_updated_image.outputs.value }}"
          echo "Current version: ${{ steps.pkg.outputs.version }}"

  build-and-push-image:
    if: ${{ needs.check-versions.outputs.is_version_mismatch == 'true' }}
    needs: check-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package.json version
        id: pkg
        run: |
          echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/rammble/web:${{ steps.pkg.outputs.version }},${{ env.REGISTRY }}/rammble/web:latest
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.NPM_ACCESS_TOKEN }}
